const loadUI = (body) => {
    
    const header = document.createElement("header");
    const headerTitle = document.createElement("h1");
    headerTitle.innerText = "BATTLESHIP"
    header.appendChild(headerTitle);
    const main = document.createElement("main");
    const footer = document.createElement("footer");
    body.appendChild(header);
    body.appendChild(main);
    body.appendChild(footer);
    const content = document.createElement("div");
    content.setAttribute("id", "content");
    main.appendChild(content);
    const newGameDiv = document.createElement("div");
    newGameDiv.classList.add("ngDiv");
    const ngh1 = document.createElement("h1");
    ngh1.classList.add("ngh1");
    ngh1.innerText = "Play against...";
    const pvpButton = document.createElement("button");
    pvpButton.classList.add("pvpButton");
    pvpButton.innerText = "a human";
    const vsText = document.createElement("p");
    vsText.classList.add("vsText");
    vsText.innerText = "OR";
    const pveButton = document.createElement("button");
    pveButton.classList.add("pveButton");
    pveButton.innerText = "an AI";
    content.appendChild(newGameDiv);
    newGameDiv.appendChild(ngh1);
    newGameDiv.appendChild(pvpButton);
    newGameDiv.appendChild(vsText);
    newGameDiv.appendChild(pveButton);
    const gameInformationDiv = document.createElement("div");
    gameInformationDiv.classList.add("giDiv");
    gameInformationDiv.classList.add("hide");
    content.appendChild(gameInformationDiv);
    const pvpForm = document.createElement("form");
    pvpForm.classList.add("pvpForm");
    const pvpSubmitButton = document.createElement("button");
    pvpSubmitButton.classList.add("pvpSubmit");
    pvpSubmitButton.innerText = "Submit";
    const pvp1Div = document.createElement("div");
    pvp1Div.classList.add("pvp1Div");
    const pvp1Label = document.createElement("label");
    pvp1Label.setAttribute("for", "pvp1Input");
    pvp1Label.innerText = "Player 1 - Enter name: "
    const pvp1Input = document.createElement("input");
    pvp1Input.setAttribute("name", "pvp1Input");
    pvp1Input.setAttribute("id", "pvp1Input");
    pvp1Input.required = true;
    const pvp2Div = document.createElement("div");
    pvp2Div.classList.add("pvp2Div");
    const pvp2Label = document.createElement("label");
    pvp2Label.setAttribute("for", "pvp2Input");
    pvp2Label.innerText = "Player 2 - Enter name: ";
    const pvp2Input = document.createElement("input");
    pvp2Input.required = true;
    pvp2Input.setAttribute("name", "pvp2Input");
    pvp2Input.setAttribute("id", "pvp2Input");
    gameInformationDiv.appendChild(pvpForm);
    pvpForm.appendChild(pvp1Div);
    pvp1Div.appendChild(pvp1Label);
    pvp1Div.appendChild(pvp1Input);
    pvpForm.appendChild(pvp2Div);
    pvp2Div.appendChild(pvp2Label);
    pvp2Div.appendChild(pvp2Input);
    pvpForm.appendChild(pvpSubmitButton);
    const pveForm = document.createElement("form");
    pveForm.classList.add("pveForm");
    const pveSubmitButton = document.createElement("button");
    pveSubmitButton.classList.add("pveSubmit");
    pveSubmitButton.innerText = "Submit";
    const pve1Div = document.createElement("div");
    pve1Div.classList.add("pve1Div");
    const pve1Label = document.createElement("label");
    pve1Label.setAttribute("for", "pve1Input");
    pve1Label.innerText = "Player 1 - Enter name: "
    const pve1Input = document.createElement("input");
    pve1Input.setAttribute("name", "pve1Input");
    pve1Input.setAttribute("id", "pve1Input");
    pve1Input.required = true;
    gameInformationDiv.appendChild(pveForm);
    pveForm.appendChild(pve1Div);
    pve1Div.appendChild(pve1Label);
    pve1Div.appendChild(pve1Input);
    pveForm.appendChild(pveSubmitButton);
    const prepParent = document.createElement("div");
    prepParent.classList.add("prepParent");
    content.appendChild(prepParent);
    const gameSection = document.createElement("div");
    gameSection.classList.add("gs");
    const gsScoreboardDiv = document.createElement("div");
    gsScoreboardDiv.classList.add("scDiv");
    const gsMessage = document.createElement("p");
    gsMessage.classList.add("gsMessage");
    gsMessage.innerText = "Message: ";
    const scoreContainer = document.createElement("div");
    scoreContainer.classList.add("scores");
    const p1Score = document.createElement("p");
    p1Score.classList.add("pscoreboard1");
    p1Score.innerText = "Player 1 has 5 ships left.";
    const p2Score = document.createElement("p");
    p2Score.classList.add("pscoreboard2");
    p2Score.innerText = "Player 2 has 5 ships left.";
    const boardContainer = document.createElement("div");
    boardContainer.classList.add("boardContainer");
    const gsLeft = document.createElement("div");
    gsLeft.classList.add("gsLeft");
    const gsLeftOverlay = document.createElement("div");
    gsLeftOverlay.classList.add("gslO");
    const gsRight = document.createElement("div");
    gsRight.classList.add("gsRight");
    const gsRightOverlay = document.createElement("div");
    gsRightOverlay.classList.add("gsrO");
    gameSection.appendChild(gsScoreboardDiv);
    gsScoreboardDiv.appendChild(gsMessage);
    gsScoreboardDiv.appendChild(scoreContainer);
    scoreContainer.appendChild(p1Score);
    scoreContainer.appendChild(p2Score);
    gameSection.appendChild(boardContainer);
    boardContainer.appendChild(gsLeft);
    boardContainer.appendChild(gsRight);
    const gsLeftH2 = document.createElement("h2");
    gsLeftH2.classList.add("gsh2");
    gsLeftH2.classList.add("p1name");
    gsLeftH2.innerText = "Player 1: ";
    const gsRightH2 = document.createElement("h2");
    gsRightH2.classList.add("gsh2")
    gsRightH2.classList.add("p2name");
    gsRightH2.innerText = "Player 2: ";
    const p1Board = document.createElement("div");
    p1Board.setAttribute("id", "p1Board");
    const p2Board = document.createElement("div");
    p2Board.setAttribute("id", "p2Board");
    gsLeft.appendChild(gsLeftOverlay);
    gsLeft.appendChild(gsLeftH2);
    gsLeft.appendChild(p1Board);
    gsRight.appendChild(gsRightOverlay);
    gsRight.appendChild(gsRightH2);
    gsRight.appendChild(p2Board);
    const rowCreator = (grid, order, rowNumber) => {
        (order === 1) ? order = "a" : order = "b";
        for (let i = 0; i < 10; i++) {
            const box = document.createElement("div");
            box.classList.add("box");
            box.classList.add(`board_${order}`);
            box.setAttribute("id", `m_${order}_${i}${rowNumber}`);
            grid.appendChild(box);
        }

    }
    rowCreator(p1Board, 1, 0);
    rowCreator(p1Board, 1, 1);
    rowCreator(p1Board, 1, 2);
    rowCreator(p1Board, 1, 3);
    rowCreator(p1Board, 1, 4);
    rowCreator(p1Board, 1, 5);
    rowCreator(p1Board, 1, 6);
    rowCreator(p1Board, 1, 7);
    rowCreator(p1Board, 1, 8);
    rowCreator(p1Board, 1, 9);
    rowCreator(p2Board, 2, 0);
    rowCreator(p2Board, 2, 1);
    rowCreator(p2Board, 2, 2);
    rowCreator(p2Board, 2, 3);
    rowCreator(p2Board, 2, 4);
    rowCreator(p2Board, 2, 5);
    rowCreator(p2Board, 2, 6);
    rowCreator(p2Board, 2, 7);
    rowCreator(p2Board, 2, 8);
    rowCreator(p2Board, 2, 9);
    content.appendChild(gameSection);

};

export default loadUI;